---
# RISC OS 64 CI build
#
# The 'release' job is triggered when a tag starting with a 'v' is created,
# which will create a GitHub release for the repository with the name of the
# version tag. The release will be a draft, and should be updated with
# changes as you see fit.
#

name: RISC OS

# Controls when the action will run. Triggers the workflow on:
#   * push on any branch.
#   * tag creation for tags beginning with a 'v'
on:
  push:
    branches: ["master"]
    tags: ["v*"]
  # Pull request events happen on pull request state transitions, so we probably don't want this here.
  pull_request:
    branches: ["*"]
    paths:
      # Only run the job if the changes affect the C library
      - 'clib/**'
      - 'absolutes/**'
      - 'utilities/**'
      - 'modules/**'
      - 'robuild64'
      - 'VersionNum'
      - 'tests/**'

concurrency:
  # Be nice to the build service and only submit a single job at a time.
  group: riscos-build-service
  cancel-in-progress: false

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read

    outputs:
      version: ${{ steps.version.outputs.version }}
      leafname_bin: ${{ steps.version.outputs.leafname_bin }}
      leafname_lib: ${{ steps.version.outputs.leafname_lib }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Build the C library
        run: |
          cd clib
          make export

      - name: Smoke test the C library
        run: |
          cd clib
          tests/test-install.sh

      - name: Build the absolutes
        run: |
          cd absolutes
          make all

      - name: Build the modules
        run: |
          cd modules
          make all

      - name: Build the utilities
        run: |
          cd utilities
          make all

      - name: Build the archives
        run: |
          zip -9r RISCOS64-Binaries.zip absolutes/*,ff8 modules/*,ffa utilities/*,ffc
          cd clib/export ; zip -9r ../../RISCOS64-CLib.zip *

      - name: Give the output a versioned name
        id: version
        run: |
          if [[ -f VersionNum ]] ; then
              version=$(sed '/MajorVersion / ! d ; s/.*MajorVersion *"\(.*\)"/\1/' VersionNum)
          else
              version=$(git rev-parse --short HEAD)
          fi
          echo "This is version: $version"
          leafname_bin="RISCOS64-Binaries-$version.zip"
          leafname_lib="RISCOS64-CLib-$version.zip"
          mv RISCOS64-Binaries.zip "RISCOS64-Binaries-$version.zip"
          mv RISCOS64-CLib.zip "RISCOS64-CLib-$version.zip"

          echo "version=$version" >> $GITHUB_OUTPUT
          echo "leafname_lib=$leafname_lib" >> $GITHUB_OUTPUT
          echo "leafname_bin=$leafname_bin" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: RISCOS64-binaries
          path: ${{ steps.version.outputs.leafname_bin }}

      - uses: actions/upload-artifact@v4
        with:
          name: RISCOS64-clib
          path: ${{ steps.version.outputs.leafname_lib }}

  test:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Download built RISC OS 64 binaries
        uses: actions/download-artifact@v4
        with:
          name: RISCOS64-binaries

      - name: Extract RISC OS 64 binaries
        run: |
          unzip "${{ needs.build.outputs.leafname_bin }}"

      - name: Obtain prerequisite build tool
        run: |
          # Fetch the build client
          curl -s -L -o riscos-build-online https://github.com/gerph/robuild-client/releases/download/v0.07/riscos-build-online && chmod +x riscos-build-online

      - name: Run tests on Absolutes
        run: |
          tests/run-tests.sh absolutes

      - name: Run tests on Modules
        run: |
          tests/run-tests.sh modules

      - name: Run tests on Utilities
        run: |
          tests/run-tests.sh utilities

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'test-results/Test-*.xml'
          comment: true
          group_suite: true
          verbose_summary: true
          detailed_summary: true
          include_passed: true
          include_time_in_summary: true

  # The release only triggers when the thing that was pushed was a tag starting with 'v'
  release:
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - name: Download built RISC OS 64 binaries
        uses: actions/download-artifact@v4
        with:
          name: RISCOS64-binaries

      - name: Download built RISC OS 64 binaries
        uses: actions/download-artifact@v4
        with:
          name: RISCOS64-clib

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          prerelease: false
          draft: true
          artifacts: "${{ needs.build.outputs.leafname_bin }},${{ needs.build.outputs.leafname_lib }}"
          artifactContentType: application/zip
